# Generated by Django 3.1.6 on 2021-02-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0002_auto_20210203_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='brand',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='holder',
            field=models.CharField(default='', max_length=70),
        ),
    ]
