# Generated by Django 3.1.6 on 2021-02-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('holder', models.FileField(max_length=70, upload_to=None)),
                ('number', models.BinaryField()),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
