# Generated by Django 3.1.6 on 2021-02-03 13:58

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='number_data',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='holder',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='number_data', hash_key='f164ec6bd6fbc4aef5647abc15199da0f9badcc1d2127bde2087ae0d794a9a0b', max_length=66, null=True),
        ),
    ]
